In [ ]:
pip install pandas

In [4]:
import pandas as pd
df=pd.read_csv('customer_shopping_behavior.csv')

In [7]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [6]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [7]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [9]:
df['Review Rating'] =df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [10]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [11]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')

In [12]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [13]:
labels=['Young Adult','Adult','Middle-aged','Seniour']
df['age_group']=pd.qcut(df['age'],q=4,labels=labels)

In [14]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63      Seniour
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [16]:
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly':7,
    'Monthly':30,
    'Quaterly':90,
    'Bi-Weekly': 14,
    'Annually':365,
    'Every 3 Months':90
}
df['purchase_frequency_days']=df['frequency_of_purchases'].map(frequency_mapping)

In [17]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                     14.0            Fortnightly
1                     14.0            Fortnightly
2                      7.0                 Weekly
3                      7.0                 Weekly
4                    365.0               Annually
5                      7.0                 Weekly
6                      NaN              Quarterly
7                      7.0                 Weekly
8                    365.0               Annually
9                      NaN              Quarterly

In [18]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [19]:
(df['discount_applied']==df['promo_code_used']).all()

np.True_

In [20]:
df=df.drop('promo_code_used',axis=1)

In [21]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [22]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in .\.conda\envs\notebook-env\Lib\site-packages (2.9.13)
Requirement already satisfied: sqlalchemy in .\.conda\envs\notebook-env\Lib\site-packages (2.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in .\.conda\envs\notebook-env\Lib\site-packages (from sqlalchemy) (4.16.0)
Note: you may need to restart the kernel to use updated packages.

In [23]:
pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in .\.conda\envs\notebook-env\Lib\site-packages (26.7.0)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import mysql.connector
connection=mysql.connector.connect(
    host="localhost",
    user="root",
    password="Root123",
    database="Local instance MySQL80",
    port="3306"
)
print("connect successfully")

In [ ]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://USER:Root123@localhost:3306/Local instance MySQL80")

df = pd.read_sql("SELECT * FROM your_table LIMIT 10", engine)
df

In [ ]:
pip install sqlalchemy pymysql pandas

In [ ]:
import mysql.connector
import pandas as pd

# Define your connection credentials (matching your MySQL Workbench details)
connection = mysql.connector.connect(
    host="localhost",       # Using 127.0.0.1 forces a reliable TCP connection
    user="root",            # Default username
    password="Root123", # Replace with your actual password
    database="customer" # Replace with your schema/database name
)

# Verify the connection works by pulling data into a Pandas DataFrame
query = "SELECT * FROM your_table_name;" # Replace with your table name
df = pd.read_sql_query(query, connection)

# Display the first few rows of your data
print(df.head())

# Always close the connection when you're done
connection.close()

In [ ]:
import mysql.connector

In [ ]:
pip install mysql.connector

In [ ]:
try:
  db=mysql.connector.connect(
    host="127.0.0.1",
    user="root",
    password="Root123",
    database="project",
    port=3306
  )
  if mydb.is_connected():
      print("MySql connected successfully")
except mysql.connector.Error as e:
    print("Error:",e)

In [ ]:
%pip install --upgrade--force-reinstall  mysql-connector-python

In [ ]:
pip install --upgrade mysql-connector-python

In [ ]:
import mysql.connector
print(mysql.connector.__version__)

In [ ]:
pip install mysql-connector-python

In [ ]:
import mysql.connector

In [ ]:
db_connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Root123",
    database="customer_behavior"
)

print(db_connection)

In [ ]:
pip install pymysql

In [4]:
import pymysql

connection = pymysql.connect(
    host="localhost",
    user="root",
    password="Root123",
    database="customer_behavior"
)

In [1]:
pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in .\.conda\envs\notebook-env\Lib\site-packages (2.1.1)
Requirement already satisfied: pymysql in .\.conda\envs\notebook-env\Lib\site-packages (1.2.3)
Requirement already satisfied: typing-extensions>=4.6.0 in .\.conda\envs\notebook-env\Lib\site-packages (from sqlalchemy) (4.16.0)
Note: you may need to restart the kernel to use updated packages.

In [11]:
from sqlalchemy import create_engine

# Step 1: Connect to MySQL Workbench
username = "root"          # your MySQL username
password = "Root123" # your MySQL password
host = "localhost"         # if running locally
port = "3306"              # default MySQL port
database = "customer_behavior"  # ensure this database exists in MySQL Workbench

# Create engine using pymysql driver
engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

# Step 2: Load DataFrame into MySQL
table_name = "customer"    # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'customer' in database 'customer_behavior'.